---
name: Frequently updated for daily stats

on:
  schedule:
    - cron: "0 0 * * *" # Every day at 0:00
  workflow_dispatch: ~

jobs:
  time_blocks:
    name: Update timeblocks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update WakaTime Stats
        uses: athul/waka-readme@v0.1.5
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKA_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_TITLE: true
          BLOCKS: ⣀⣄⣤⣦⣶⣷⣿
      - name: Update activities
        uses: jamesgeorge007/github-activity-readme@v0.3.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          MAX_LINES: 10
